import type { StoreData } from './types';

export const storeData: StoreData = {
  name: 'Empório dos Óculos',
  tagline: 'O maior atacadão de óculos de Natal com preços de fábrica',
  description: 'Sua ótica de confiança em Lagoa Nova. Oferecemos as melhores marcas de armações, lentes de alta tecnologia e atendimento especializado para cuidar da sua saúde visual.',
  aboutText: 'Desde nossa fundação, a Empório dos Óculos tem como missão democratizar o acesso a óculos de qualidade em Natal. Combinamos a maior variedade de armações modernas, laboratório próprio de montagem computadorizada rápida e preços competitivos de atacado para garantir a melhor experiência para você e sua família.',
  aboutImage: 'https://images.unsplash.com/photo-1591076482161-42ce6da69f67?auto=format&fit=crop&q=80&w=1200',
  phone: '(84) 2030-3145',
  phoneFormatted: '8420303145',
  whatsappNumber: '5584988094270', // WhatsApp atualizado do novo HTML
  whatsappMessage: 'Olá! Gostaria de agendar um atendimento ou solicitar orçamento de óculos.',
  address: 'Av. Prudente de Morais, 3720 – Loja 24, Bloco B (Carrefour Zona Sul – Lagoa Nova), Natal/RN – CEP: 59.020-510',
  googleMapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3969.213271167727!2d-35.216391!3d-5.811394599999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x7b301c435be799b%3A0xe54e6fa16b0b2302!2sAv.%20Prudente%20de%20Morais%2C%203720%20-%20Lagoa%20Nova%2C%20Natal%20-%20RN%2C%2059020-400!5e0!3m2!1spt-BR!2sbr!4v1710000000000!5m2!1spt-BR!2sbr',
  googleMapsDirectionsUrl: 'https://maps.app.goo.gl/u1XvXQ5V9c7s6b6C7',
  businessHours: {
    weekdays: 'Segunda a Sexta: 08:00 às 21:00',
    saturday: 'Sábado: 08:00 às 18:00',
    sunday: 'Domingo: Fechado',
  },
  colors: {
    primaryHex: '#E30613', // Vermelho Oficial
    accentHex: '#0f172a',  // Slate Escuro (Ray-Ban style)
  },
  typography: {
    displayFontFamily: 'Outfit',
    bodyFontFamily: 'Inter',
    importUrl: 'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Outfit:wght@400;600;800;900&display=swap',
  },
  instagramUrl: 'https://www.instagram.com/emporiodosoculosrn/',
  facebookUrl: 'https://www.facebook.com/emporiodosoculosrn/',
  brands: [
    { name: 'Ray-Ban', desc: 'A lenda do estilo' },
    { name: 'Oakley', desc: 'Performance extrema' },
    { name: 'Persol', desc: 'Arte em acetato' },
    { name: 'Versace', desc: 'Glamour de passarela' },
    { name: 'Prada', desc: 'Vanguardismo e design' }
  ],
  features: [
    {
      title: 'Laboratório Computadorizado',
      description: 'Montagem de óculos em tempo recorde com precisão digital alemã.',
      iconName: 'Activity',
    },
    {
      title: 'Preço de Atacado',
      description: 'Preços de fábrica direto para você, com condições especiais no pix.',
      iconName: 'Tag',
    },
    {
      title: 'Exame Rápido',
      description: 'Estrutura parceira para exames computadorizados e triagem da visão.',
      iconName: 'Eye',
    },
  ],
  products: [
    {
      id: 'grau-1',
      name: 'Acetato Italiano Classic',
      description: 'Acetato premium polido à mão. Armação resistente com alta flexibilidade e design retangular atemporal.',
      price: 'R$ 149,90',
      iconName: 'Glasses',
      imageUrl: 'https://images.unsplash.com/photo-1591076482161-42ce6da69f67?auto=format&fit=crop&q=80&w=600',
      category: 'grau',
      brand: 'Empório Bold',
      installments: 'ou 3x de R$ 49,96 sem juros',
    },
    {
      id: 'grau-2',
      name: 'Titanium Flex Air',
      description: 'Feita em liga de titânio cirúrgico ultra leve (apenas 8 gramas). Conforto incomparável e resistência extrema.',
      price: 'R$ 299,90',
      iconName: 'Glasses',
      imageUrl: 'https://images.unsplash.com/photo-1508296695146-257a814070b4?auto=format&fit=crop&q=80&w=600',
      category: 'grau',
      brand: 'Titan Line',
      installments: 'ou 6x de R$ 49,98 sem juros',
    },
    {
      id: 'grau-3',
      name: 'Gatinho Bold Tortoise',
      description: 'Formato gatinho clássico com acabamento tartaruga brilhante. Levanta o olhar com elegância e sofisticação.',
      price: 'R$ 189,90',
      iconName: 'Glasses',
      imageUrl: 'https://images.unsplash.com/photo-1509695507497-903c140c43b0?auto=format&fit=crop&q=80&w=600',
      category: 'grau',
      brand: 'Vogue Style',
      installments: 'ou 4x de R$ 47,47 sem juros',
    },
    {
      id: 'sol-1',
      name: 'Wayfarer Classic',
      description: 'O modelo clássico atemporal que definiu gerações. Armação resistente de acetato com proteção UV400 completa.',
      price: 'R$ 910,79',
      iconName: 'Sun',
      imageUrl: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&q=80&w=600',
      category: 'sol',
      brand: 'Ray-Ban',
      installments: 'ou 10x de R$ 91,07 sem juros',
      tag: 'Novo',
    },
    {
      id: 'sol-2',
      name: 'Holbrook',
      description: 'Design clássico combinado com a tecnologia de performance Oakley. Lentes Prizm para cores e contraste otimizados.',
      price: 'R$ 1.199,00',
      iconName: 'Sun',
      imageUrl: 'https://images.unsplash.com/photo-1509695507497-903c140c43b0?auto=format&fit=crop&q=80&w=600',
      category: 'sol',
      brand: 'Oakley',
      installments: 'ou 12x de R$ 99,91 sem juros',
      tag: 'Oferta',
    },
    {
      id: 'sol-3',
      name: 'PO0649',
      description: 'Óculos vintage italiano com a icônica seta de metal prateada Persol e tecnologia de hastes flexíveis Meflecto.',
      price: 'R$ 1.450,00',
      iconName: 'Sun',
      imageUrl: 'https://images.unsplash.com/photo-1508296695146-257a814070b4?auto=format&fit=crop&q=80&w=600',
      category: 'sol',
      brand: 'Persol',
      installments: 'ou 10x de R$ 145,00 sem juros',
    },
    {
      id: 'sol-4',
      name: 'VE2225',
      description: 'Design de passarela italiano com hastes grossas douradas estilizadas e lentes escuras de altíssima proteção.',
      price: 'R$ 2.200,00',
      iconName: 'Sun',
      imageUrl: 'https://images.unsplash.com/photo-1577803645773-f96470509666?auto=format&fit=crop&q=80&w=600',
      category: 'sol',
      brand: 'Versace',
      installments: 'ou 12x de R$ 183,33 sem juros',
      tag: 'Premium',
    },
    {
      id: 'sol-5',
      name: 'Aviator',
      description: 'O clássico óculos gota de metal dourado leve. Lentes clássicas G-15 verde escuro que oferecem alto contraste visual.',
      price: 'R$ 850,00',
      iconName: 'Sun',
      imageUrl: 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?auto=format&fit=crop&q=80&w=600',
      category: 'sol',
      brand: 'Ray-Ban',
      installments: 'ou 10x de R$ 85,00 sem juros',
    },
    {
      id: 'sol-6',
      name: 'Clubmaster',
      description: 'Inspirado na atitude intelectual dos anos 50. Design de sobrancelha preta marcada com aro inferior dourado e lentes escuras.',
      price: 'R$ 980,00',
      iconName: 'Sun',
      imageUrl: 'https://images.unsplash.com/photo-1589782182703-e8692268880c?auto=format&fit=crop&q=80&w=600',
      category: 'sol',
      brand: 'Ray-Ban',
      installments: 'ou 10x de R$ 98,00 sem juros',
    },
    {
      id: 'lente-1',
      name: 'Lentes Blue Control Pro',
      description: 'Tratamento antirreflexo inteligente que bloqueia a luz azul nociva de smartphones e computadores. Reduz fadiga visual.',
      price: 'R$ 179,00',
      iconName: 'ShieldCheck',
      imageUrl: 'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?auto=format&fit=crop&q=80&w=600',
      category: 'lente',
      brand: 'Hoya Digital',
      installments: 'ou 3x de R$ 59,66 sem juros',
    },
    {
      id: 'lente-2',
      name: 'Lentes Fotocromáticas Smart',
      description: 'Tecnologia que adapta a cor das lentes à intensidade solar: totalmente transparente dentro de casa e escura sob o sol.',
      price: 'R$ 259,00',
      iconName: 'ShieldCheck',
      imageUrl: 'https://images.unsplash.com/photo-1591076482161-42ce6da69f67?auto=format&fit=crop&q=80&w=600',
      category: 'lente',
      brand: 'Transitions VII',
      installments: 'ou 5x de R$ 51,80 sem juros',
      hasSplitVisual: true,
    },
    {
      id: 'lente-3',
      name: 'Multifocais HD Digital',
      description: 'Produzidas por computador com mapeamento de alta definição do seu campo de visão para transição suave de longe e perto.',
      price: 'Sob Consulta',
      iconName: 'ShieldCheck',
      imageUrl: 'https://images.unsplash.com/photo-1509695507497-903c140c43b0?auto=format&fit=crop&q=80&w=600',
      category: 'lente',
      brand: 'Essilor Varilux',
      installments: 'Consulte parcelas no balcão',
    },
  ],
};;
